[2025-07-15T12:09:42.133+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_rates_daily_update.run_currency_pipeline scheduled__2025-07-14T00:00:00+00:00 [queued]>
[2025-07-15T12:09:42.138+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_rates_daily_update.run_currency_pipeline scheduled__2025-07-14T00:00:00+00:00 [queued]>
[2025-07-15T12:09:42.139+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-15T12:09:42.151+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_currency_pipeline> on 2025-07-14 00:00:00+00:00
[2025-07-15T12:09:42.155+0000] {standard_task_runner.py:60} INFO - Started process 193 to run task
[2025-07-15T12:09:42.158+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_rates_daily_update', 'run_currency_pipeline', 'scheduled__2025-07-14T00:00:00+00:00', '--job-id', '473', '--raw', '--subdir', 'DAGS_FOLDER/currency_rates_daily_update.py', '--cfg-path', '/tmp/tmpahnkl7us']
[2025-07-15T12:09:42.159+0000] {standard_task_runner.py:88} INFO - Job 473: Subtask run_currency_pipeline
[2025-07-15T12:09:42.206+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_rates_daily_update.run_currency_pipeline scheduled__2025-07-14T00:00:00+00:00 [running]> on host 2d5a57b99ef6
[2025-07-15T12:09:42.268+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_rates_daily_update' AIRFLOW_CTX_TASK_ID='run_currency_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-07-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-14T00:00:00+00:00'
[2025-07-15T12:09:42.269+0000] {logging_mixin.py:188} INFO - Checking last date in prod table...
[2025-07-15T12:09:50.114+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/etl/etl_currencies.py", line 118, in run_currency_pipeline
    start_date = get_start_date_from_db()
  File "/opt/airflow/etl/etl_currencies.py", line 22, in get_start_date_from_db
    with get_connection() as conn:
  File "/opt/airflow/db/connection.py", line 8, in get_connection
    return psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres_db" to address: Name or service not known

[2025-07-15T12:09:50.138+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=currency_rates_daily_update, task_id=run_currency_pipeline, execution_date=20250714T000000, start_date=20250715T120942, end_date=20250715T120950
[2025-07-15T12:09:50.151+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 473 for task run_currency_pipeline (could not translate host name "postgres_db" to address: Name or service not known
; 193)
[2025-07-15T12:09:50.193+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-15T12:09:50.209+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
